# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: espec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65spec.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0cshared.proto\"?\n\x13\x45SPECMonitoringTask\x12\x15\n\rlookbackWeeks\x18\x01 \x01(\x05\x12\x11\n\tdesignIds\x18\x02 \x03(\t2\x9d\x01\n\x05\x45SPEC\x12\x34\n\theartbeat\x12\x11.HeartBeatRequest\x1a\x12.HeartBeatResponse\"\x00\x12%\n\x04task\x12\x0c.TaskRequest\x1a\r.TaskResponse\"\x00\x12\x37\n\ntaskStatus\x12\x12.TaskStatusRequest\x1a\x13.TaskStatusResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'espec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ESPECMONITORINGTASK._serialized_start=86
  _ESPECMONITORINGTASK._serialized_end=149
  _ESPEC._serialized_start=152
  _ESPEC._serialized_end=309
# @@protoc_insertion_point(module_scope)
