# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshared.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\")\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03\x66\x61\x62\x18\x02 \x01(\t\")\n\x10HeartBeatRequest\x12\x15\n\rcorrelationId\x18\x01 \x01(\t\"$\n\x11HeartBeatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"x\n\x0cQueryRequest\x12\x15\n\rcorrelationId\x18\x01 \x01(\t\x12\r\n\x05query\x18\x0b \x01(\t\x12\x1b\n\x08userinfo\x18\x0c \x01(\x0b\x32\t.UserInfo\x12%\n\x07payload\x18\r \x01(\x0b\x32\x14.google.protobuf.Any\"9\n\rQueryResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\"v\n\x0bTaskRequest\x12\x15\n\rcorrelationId\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x0b \x01(\t\x12\x1b\n\x08userinfo\x18\x0c \x01(\x0b\x32\t.UserInfo\x12%\n\x07payload\x18\r \x01(\x0b\x32\x14.google.protobuf.Any\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"H\n\x11TaskStatusRequest\x12\x15\n\rcorrelationId\x18\x01 \x01(\t\x12\x0e\n\x06taskId\x18\x0b \x01(\t\x12\x0c\n\x04task\x18\x0c \x01(\t\"B\n\x12TaskStatusResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFO._serialized_start=73
  _USERINFO._serialized_end=114
  _HEARTBEATREQUEST._serialized_start=116
  _HEARTBEATREQUEST._serialized_end=157
  _HEARTBEATRESPONSE._serialized_start=159
  _HEARTBEATRESPONSE._serialized_end=195
  _QUERYREQUEST._serialized_start=197
  _QUERYREQUEST._serialized_end=317
  _QUERYRESPONSE._serialized_start=319
  _QUERYRESPONSE._serialized_end=376
  _TASKREQUEST._serialized_start=378
  _TASKREQUEST._serialized_end=496
  _TASKRESPONSE._serialized_start=498
  _TASKRESPONSE._serialized_end=528
  _TASKSTATUSREQUEST._serialized_start=530
  _TASKSTATUSREQUEST._serialized_end=602
  _TASKSTATUSRESPONSE._serialized_start=604
  _TASKSTATUSRESPONSE._serialized_end=670
# @@protoc_insertion_point(module_scope)
