# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: space_charts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12space_charts.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0cshared.proto\"\x18\n\x06\x43ommon\x12\x0e\n\x06module\x18\x01 \x01(\t\"{\n\x11QuerySpaceSamples\x12\x0c\n\x04\x63hId\x18\x01 \x01(\x05\x12\r\n\x05\x63kcId\x18\x02 \x01(\x05\x12\x0f\n\x07samples\x18\x03 \x01(\x05\x12\x14\n\x0clookbackDays\x18\x04 \x01(\x05\x12\x11\n\tstartDate\x18\x05 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x06 \x01(\t\"6\n\x17QuerySpaceChartMetadata\x12\x0c\n\x04\x63hId\x18\x01 \x01(\x05\x12\r\n\x05\x63kcId\x18\x02 \x01(\x05\"A\n\x1c\x43riticalChartsMonitoringTask\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x11\n\tdesignIds\x18\x0b \x03(\t\"-\n\x1b\x43hronicChartsMonitoringTask\x12\x0e\n\x06module\x18\x01 \x01(\t\"+\n\x19\x46ixedChartsMonitoringTask\x12\x0e\n\x06module\x18\x01 \x01(\t2\xcd\x01\n\x0bSpaceCharts\x12\x34\n\theartbeat\x12\x11.HeartBeatRequest\x1a\x12.HeartBeatResponse\"\x00\x12(\n\x05query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12%\n\x04task\x12\x0c.TaskRequest\x1a\r.TaskResponse\"\x00\x12\x37\n\ntaskStatus\x12\x12.TaskStatusRequest\x1a\x13.TaskStatusResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'space_charts_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMON._serialized_start=93
  _COMMON._serialized_end=117
  _QUERYSPACESAMPLES._serialized_start=119
  _QUERYSPACESAMPLES._serialized_end=242
  _QUERYSPACECHARTMETADATA._serialized_start=244
  _QUERYSPACECHARTMETADATA._serialized_end=298
  _CRITICALCHARTSMONITORINGTASK._serialized_start=300
  _CRITICALCHARTSMONITORINGTASK._serialized_end=365
  _CHRONICCHARTSMONITORINGTASK._serialized_start=367
  _CHRONICCHARTSMONITORINGTASK._serialized_end=412
  _FIXEDCHARTSMONITORINGTASK._serialized_start=414
  _FIXEDCHARTSMONITORINGTASK._serialized_end=457
  _SPACECHARTS._serialized_start=460
  _SPACECHARTS._serialized_end=665
# @@protoc_insertion_point(module_scope)
